=== ENSATANGER/GestionEnsaTanger/GestionEnsaTanger/XML_FILES/Filieres.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="ENSA_TANGER">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Filiere" minOccurs="0" maxOccurs="6">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Niveau" minOccurs="0" maxOccurs="3">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Eleve" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Notes" minOccurs="0" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="Note" minOccurs="0" maxOccurs="unbounded">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                        <xs:element name="code_mat"></xs:element>
                                                                            <xs:element name="note"></xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="Moyenne" minOccurs="0" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="niveau"></xs:element>
                                                                <xs:element name="moyenne"></xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="code" type="xs:string"/>
                                                <xs:attribute name="nom" type="xs:string"/>
                                                <xs:attribute name="prenom" type="xs:string"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="code" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="code" type="xs:string"/>
                        <xs:attribute name="designation" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ENSATANGER/GestionEnsaTanger/GestionEnsaTanger/XML_FILES/ENSA_TANGER.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="ENSA_TANGER.xsl"?>
<ENSA_TANGER xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="Filieres Filieres.xsd">
  <Filiere code="AP">
    <Niveau code="AP1"></Niveau>
    <Niveau code="AP2"></Niveau>
  </Filiere>
  <Filiere code="GINF">
    <Niveau code="GINF1">
    </Niveau>
    <Niveau code="GINF2">
    </Niveau>
    <Niveau code="GINF3">
    </Niveau>
  </Filiere>
  <Filiere code="GIL">
    <Niveau code="GIL1"></Niveau>
    <Niveau code="GIL2"></Niveau>
    <Niveau code="GIL3"></Niveau>
  </Filiere>
  <Filiere code="GSTR">
    <Niveau code="GSTR1">
      <Eleve id="6" code="LF59111" nom="LAARBI" prenom="Cheb" niveau="GSTR1" code_fil="GSTR">
        <DateSuppression date="08 April 2023" heure="13:16:26" />
      </Eleve>
    </Niveau>
    <Niveau code="GSTR2"></Niveau>
    <Niveau code="GSTR3"></Niveau>
  </Filiere>
  <Filiere code="GSEA">
    <Niveau code="GSEA1"></Niveau>
    <Niveau code="GSEA2"></Niveau>
    <Niveau code="GSEA3"></Niveau>
  </Filiere>
  <Filiere code="G3EI">
    <Niveau code="G3EI1"></Niveau>
    <Niveau code="G3EI2"></Niveau>
    <Niveau code="G3EI3"></Niveau>
  </Filiere>
</ENSA_TANGER>
